version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: net.minecraftforge.gradle:ForgeGradle
    versions:
    - 4.0.15
